### ISSUE TITLE
Scribble-supervision code

### ISSUE THREAD

**Issue by Karol-G** [HiLab-git/WORD#5]
Hey,

Thank you for the great dataset! I read the paper and was impressed by your scribble-supervision approach. However, I was unable to find the implementation in this repo. It was stated in the paper that the implementation was public. Could you be so kind as to direct me to the scribble-supervision code? 

The relevant parts for me would especially be these:
- The implementation of nnU-Net V2 with ResUNet 2D backbone
- The implementation of the pCE + L_ent + L_ivm losses

I would also be grateful if the trained weights for the scribble-supervision model could be made public.

Thank you in advance!

Kind regards,
Karol

**Comment by Luoxd1996** [comment]
Hi，
If you want to nnUNet framework to train ResUNet please check [here](https://github.com/Luoxd1996/nnunet_mini/blob/e70b2d6fc5d97ea10cdce6c0cb03f5083216def3/nnUNetTrainer.py#L306) and the implementations of pCE, Lent, Livm can be found [here](https://github.com/HiLab-git/WSL4MIS). Due to the work have was done two years ago, I haven't the checkpoint now, but I believe it can be reproduced easily. Any questions, send me an email.
Best,
Xiangde Luo.

**Comment by Karol-G** [comment]
Hey @Luoxd1996,

Thanks a lot!

Best,
Karol
